Pipeline improvements

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -4,6 +4,7 @@ variables:
   OS: "centos"
   OS_VERSION: "8"
   IMAGE_NAME: "gitlab-master.nvidia.com:5005/cuda-installer/opengl"
+  BUILDER_IMAGE_NAME: "${IMAGE_NAME}/gitlab-builder"
   REGISTRIES: "nvcr.io/nvidia/opengl docker.io/nvidia/opengl urm.nvidia.com/sw-gpu-cuda-installer-docker-local/opengl"
 
 
@@ -21,7 +22,7 @@ stages:
 
 .tags_template: &tags_definition
   tags:
-    - opengl-docker
+    - docker
 
 # builds the gitlab-builder image
 prepare:
@@ -45,13 +46,15 @@ prepare:
         RUN if [ ! -e /usr/bin/python ]; then ln -sf /usr/bin/python3 /usr/bin/python; fi
         RUN curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
       EOF
-    - docker build -t gitlab-opengl-builder .
+    - docker build -t ${BUILDER_IMAGE_NAME} --cache-from ${BUILDER_IMAGE_NAME} .
+    - docker push ${BUILDER_IMAGE_NAME}
     - docker images
   <<: *tags_definition
 
 .base_template: &base_definition
   stage: base
-  image: gitlab-opengl-builder
+  image: ${BUILDER_IMAGE_NAME}
+  retry: 2
   <<: *tags_definition
   script:
     - if [[ "${NO_OS_SUFFIX}" == "true" ]]; then
@@ -73,7 +76,8 @@ prepare:
 
 .glvnd_template: &glvnd_definition
   stage: glvnd
-  image: gitlab-opengl-builder
+  image: ${BUILDER_IMAGE_NAME}
+  retry: 2
   <<: *tags_definition
   script:
     - VERSION="${CI_JOB_NAME:1}"
@@ -107,27 +111,41 @@ prepare:
 
 .scan_template: &scan_definition
   stage: scan
-  image: gitlab-opengl-builder
+  image: ${BUILDER_IMAGE_NAME}
   <<: *tags_definition
   script:
-    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-master.nvidia.com/sectooling/scanning/contamer.git
-    - cd contamer
-    - pip3 install -r requirements.txt
-    - docker pull ${IMAGE_TO_SCAN}
-    - python3 contamer.py -ls --fail-on-non-os ${IMAGE_TO_SCAN}
-    - export CONTAMER_RET=$?
-    - docker rmi -f ${IMAGE_TO_SCAN}
-    - >-
-      if [[ $CONTAMER_RET -ne 0 ]]; then
-        exit 1;
+    - |
+      if [[ -z $NO_SCAN ]]; then
+        git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-master.nvidia.com/sectooling/scanning/contamer.git
+        cd contamer
+        pip3 install -r requirements.txt
+        docker pull ${IMAGE_TO_SCAN}
+
+        # CVE-2020-14352 CVE-2020-15888: librepo, lua-libs packages WAIVED via https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=3028123&cmtNo=35
+        # CVE-2020-14363 CVE-2020-14363  libX11 libx11-common
+        python3 contamer.py --debug-logs -ls --fail-on-non-os ${IMAGE_TO_SCAN} \
+            --suppress-vulns CVE-2020-14352 CVE-2020-15888 CVE-2020-14363 CVE-2020-14363 | tee /tmp/output
+        retval=$?
+
+        echo "Contamer return value: ${retval}";
+        docker rmi -f ${IMAGE_TO_SCAN}
+        if [[ $retval -ne 0 ]]; then
+            exit 1;
+        else
+            # we need to look at the output for "Traceback" because contamer doesn't return non-zero on exception failure...
+            if cat /tmp/output | grep -q "Traceback\|Exception: Image analysis failed"; then
+                exit 1;
+            fi
+        fi
       else
-        echo "Contamer return value: ${CONTAMER_RET}";
+        exit 0;
       fi
 
 
 .deploy_template: &deploy_definition
   stage: deploy
-  image: gitlab-opengl-builder
+  image: ${BUILDER_IMAGE_NAME}
+  retry: 2
   <<: *tags_definition
   script:
     - for tag in $(env | grep 'NV_.*_TAGS' | cut -f2 -d=); do
